package ttl.intern.project.forumHTTPServer;

public enum EBCode {
	NO_ACTION_SPECIFIED,
	BAD_ACTION,
	SUCCESSFUL,
	ERROR_DATABASE,
	ERROR_INPUT_BLANK,
	ERROR_LOGIN_INVALID,
	ERROR_SIGNUP_USERNAME_EXITED,
	ERROR_INVALID_TOKEN,
	ERROR_UPDATE_PASSWORD_INVALID_OLDPASS,
}
